name: 'Fetch Linode Instances'
description: 'Fetch the Linode instances with tags matching the given environment'

inputs:
  environment:
    description: 'The environment to deploy to and corresponding git branch'
    required: false
    default: |
      production=main
      staging=develop
      development=develop
  branch:
    description: 'The branch to deploy'
    required: false
    default: '${{ github.ref }}'
  linode_token:
    description: 'Linode Personal Access Token'
    required: true
  git_repo:
      description: 'The git repository to deploy'
      required: false
      default: '${{ github.repository }}'

runs:
  using: "composite"
  steps:
    - name: Setup environment
      shell: bash
      run: |
        while IFS= read -r line
        do
            IFS="=" read -a STR <<< "$line"
            if [ "${{ inputs.branch }}" == "${STR[1]}" ]; then
                echo "ENVIRONMENT=${STR[0]}" >> $GITHUB_ENV
            fi
        done <<< "${{ inputs.environment }}"

    - name: Fetch Linode instances
      shell: bash
      run: |
        curl -H "Authorization: Bearer ${{ inputs.linode_token }}" \
          https://api.linode.com/v4/linode/instances \
          | jq -c '.data[] | select((.tags[] | contains("environment:" + "${{ env.ENVIRONMENT }}")) and (.tags[] | contains("vcs:${{ inputs.git_repo }}")))' \
          > linode_instances.json
        echo "::set-output name=linode_instances::$(jq -r '[.[] | .ipv4[0]]' linode_instances.json)"
      id: linode_instances

outputs:
  linode_instances:
    description: "The IPs of the Linode instances"
    value: ${{ steps.linode_instances.outputs.linode_instances }}
